name: miMapGeo
description: Mis pruebas con Mapbox y geolocator.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  baseflow_plugin_template:
    git:
      url: git://github.com/Baseflow/baseflow_plugin_template.git
      ref: v1.0.0
  flutter:
    sdk: flutter

    
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # <<<<<<<<<<<<<<<<<<<<<<<<<<<
  # El gestor de Estado
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^4.3.2+3
  # Libreria MapBox
  # A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
  mapbox_gl:  ^0.9.0
  # Acceso al GPS del dispositivo
  # A Flutter geolocation plugin which provides easy access to platform specific location services
  geolocator: ^6.1.13
  # Herramienta para obtener la dirección de una latLng
  # A Flutter Geocoding plugin which provides easy geocoding and reverse-geocoding features.
  # locationFromAddress placemarkFromCoordinates
  geocoding: ^1.0.5
  # Manejador de FileSystem
  path_provider: ^1.6.27


dev_dependencies:
  flutter_test:
    sdk: flutter
  # Forma fácil de poner icono para la aplicación
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mappy_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/